books:
  "04A3FF912B7780":
    title: "Sherlock Holmes"
    path: "audio/sherlock_holmes"
  "11223344556677":
    title: "Harry Potter and the Goblet of Fire"
    path: "audio/Harry Potter and the Goblet of Fire"